version: '3'
services:
  # build container for the mongo-db noSQL database required by openhim-core
  mongo:
    container_name: openhim-mongodb
    ports:
      - "27017:27017"
    image: mongo:3.4

   # build container for openhim-core required by openhim-console and mediators  
  core:
    container_name: openhim-core-service
    image: jembi/openhim-core
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "7788:7788"
    depends_on:
      - mongo
  
   # build container for openhim-core for the management of chanels, clients and transactions  
  openhim-console:
    container_name: openhim-console-admin
    image: jembi/openhim-console:latest
    restart: unless-stopped
    ports:
      - "9000:80"
    healthcheck:
     test: "curl -sS http://openhim-console || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3
  
  # clean block that works with the openimis-openhim-mifos mediators
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin2834
      MYSQL_DATABASE: 'mifosmediators'
      # MYSQL_USER: root
      # MYSQL_PASSWORD: admin2834
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mifosmediators
    ports:
      - "9001:8000"
    depends_on:
      - db
